name: 'Hello World'
description: 'Greet someone and record the time'
runs:
  using: 'docker'
  image: 'Dockerfile'
outputs:
  tag:
    description: 'The generated tag'
  upload_url:
    description: 'The upload URL for this release'
